---
- name: define default maxmind download url
  shell: "echo http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
  register: maxmind_download_url
  when: license_key is not defined and license_key == ""

- name: define licensed maxmind download url
  shell: echo "https://download.maxmind.com/app/geoip_download?edition_id=133&date=20140311&suffix=tar.gz&license_key={{ license_key }}"
  register: maxmind_download_url
  when: license_key is defined and license_key != ""

- name: Upgrade GeoIPCity.dat
  action: shell {{ item }} chdir=/tmp/
  with_items:
    - wget -cO GeoIPCity.dat.gz "{{ maxmind_download_url.stdout }}"
    - tar xzfv GeoIPCity.dat.gz --strip-components=1
    - rm GeoIPCity.dat.gz
    - mkdir -p /usr/share/GeoIP
    - mv GeoIPCity.dat /usr/share/GeoIP/GeoIPCity.dat